version: "3.8"
services:
  app:
    container_name: kiosk_app
    image: yhkim951107/kiosk_app:latest
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - kiosk_app:/app
  db:
    container_name: kiosk_db
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/initdb.d:/docker-entrypoint-initdb.d
volumes:
  kiosk_app:
